apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: s3-provider
spec:
  template:
    spec:
      containers:
      - name: s3fuse
        image: ghcr.io/luizpaulorosaabrantes/s3-mounter:0.1.1
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh","-c","umount -f /var/s3"]        
        securityContext:
          privileged: true
          capabilities:
            add:
            - SYS_ADMIN          
        envFrom:
        - configMapRef:
            name: s3-config
        volumeMounts:
        - name: devfuse
          mountPath: /dev/fuse
        - name: mntdatas3fs
          mountPath: /var/s3
          mountPropagation: Bidirectional
      volumes:
      - name: devfuse
        hostPath:
          path: /dev/fuse
      - name: mntdatas3fs
        hostPath:
          path: /mnt/data-s3-fs
